"use client";
import { BusinessStatus } from "@/components/ui/StatusPill";
import Link from "next/link";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { CONTACT_CHANNELS,COMPLAINT_STATUSES,complaintTransitions,type Contact,type Complaint,type RelationLink } from "@/lib/domain/relationAdherent";
import { DOSSIER_PRIORITIES } from "@/lib/domain/dossiers";
import { createContactAction,createComplaintAction,updateComplaintAction } from "@/lib/domain/relationActions";
import { formatDateTime } from "@/lib/utils/format";
export function RelationPanel({households,contacts,complaints,links,today,initialContact=false}:{initialContact?:boolean;households:{id:string;name:string}[];contacts:Contact[];complaints:Complaint[];links:RelationLink[];today:string}) {
 const [mode,setMode]=useState<"contact"|"complaint"|null>(initialContact?"contact":null),[householdId,setHousehold]=useState(households.length===1 ? households[0].id : ""),[error,setError]=useState("");
 const [status,setStatus]=useState(""),[priority,setPriority]=useState(""),[type,setType]=useState("");
 const [pending,startTransition]=useTransition();const router=useRouter();
 const name=(id:string,fallback:string)=>households.find(h=>h.id===id)?.name ?? fallback;
 const shown=complaints.filter(p=>(!status||p.status===status)&&(!priority||p.priority===priority)&&(!type||type==="Réclamation"||p.link?.type===type));
 return <div className="space-y-4"><div className="m-actionbar"><button className="m-button" onClick={()=>{setMode("contact");setError("");}}>Nouveau contact</button><button className="m-button m-button--secondary" onClick={()=>{setMode("complaint");setError("");}}>Nouvelle réclamation</button></div>
 {mode && <form key={mode} className="m-panel space-y-3" onSubmit={e=>{
 e.preventDefault();const d=new FormData(e.currentTarget);setError("");startTransition(async()=>{
 const r=mode==="contact" ? await createContactAction({householdId,date:d.get("date"),channel:d.get("channel"),reason:d.get("reason"),summary:d.get("description"),nextAction:d.get("nextAction")}) : await createComplaintAction({householdId,receivedDate:d.get("date"),priority:d.get("priority"),reason:d.get("reason"),description:d.get("description"),linkKey:d.get("linkKey")});
 if(r.error)setError(r.error);else{setMode(null);router.refresh();}
 });
 }}><h2 className="font-semibold">{mode==="contact" ? "Consigner un contact" : "Enregistrer une réclamation"}</h2><fieldset disabled={pending} className="grid gap-3 md:grid-cols-3"><legend className="sr-only">Données de relation adhérent</legend>
 <label><span className="m-label">Adhérent</span><select className="m-field" required value={householdId} onChange={e=>setHousehold(e.target.value)}><option value="">Choisir</option>{households.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label>
 <label><span className="m-label">{mode==="contact" ? "Date du contact" : "Date de réception"}</span><input className="m-field" type="date" name="date" required max={today} defaultValue={today}/></label>
 {mode==="contact" ? <label><span className="m-label">Canal</span><select className="m-field" name="channel">{CONTACT_CHANNELS.map(s=><option key={s}>{s}</option>)}</select></label> : <label><span className="m-label">Priorité</span><select className="m-field" name="priority" defaultValue="Normal">{DOSSIER_PRIORITIES.map(s=><option key={s}>{s}</option>)}</select></label>}
 <label className="md:col-span-3"><span className="m-label">Motif</span><input className="m-field" name="reason" required minLength={3} maxLength={200}/></label>
 <label className="md:col-span-3"><span className="m-label">{mode==="contact" ? "Résumé" : "Description"}</span><textarea className="m-field" name="description" required minLength={mode==="contact" ? 3 : 10} maxLength={mode==="contact" ? 3000 : 5000}/></label>
 {mode==="contact" ? <label className="md:col-span-3"><span className="m-label">Action suivante (facultative)</span><input className="m-field" name="nextAction" maxLength={1000}/></label> : <label className="md:col-span-3"><span className="m-label">Rattachement facultatif</span><select key={householdId} className="m-field" name="linkKey"><option value="">Sans rattachement</option>{links.filter(l=>l.householdId===householdId).map(l=><option key={l.key} value={l.key}>{l.label} · {l.key}</option>)}</select></label>}
 </fieldset><p className="m-help">Consignation interne uniquement : aucun email ni courrier n’est envoyé.</p><button className="m-button" disabled={pending}>Enregistrer</button>{" "}<button className="m-button m-button--secondary" type="button" disabled={pending} onClick={()=>setMode(null)}>Annuler</button>{error && <p className="m-error" role="alert">{error}</p>}</form>}
 <div className="m-filterbar"><label><span className="m-label">Statut réclamation</span><select className="m-field" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous</option>{COMPLAINT_STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label><span className="m-label">Priorité réclamation</span><select className="m-field" value={priority} onChange={e=>setPriority(e.target.value)}><option value="">Toutes</option>{DOSSIER_PRIORITIES.map(s=><option key={s}>{s}</option>)}</select></label><label><span className="m-label">Type d’interaction / rattachement</span><select className="m-field" value={type} onChange={e=>setType(e.target.value)}><option value="">Tous</option>{[...CONTACT_CHANNELS,"Réclamation","Prestation","PEC / Devis","Cotisation","Dossier"].map(s=><option key={s}>{s}</option>)}</select></label></div>
 <section className="m-panel"><h2 className="font-semibold mb-2">Timeline des contacts</h2><ol className="space-y-2">{contacts.filter(c=>!type||type===c.channel).map(c=><li key={c.id} className="border-b border-border pb-2"><p>{c.date} · <strong>{c.channel}</strong> · <Link className="text-brand underline" href={`/adherents/${c.householdId}?tab=contacts`}>{name(c.householdId,c.adherentName)}</Link> · {c.reason}</p><p className="whitespace-pre-wrap">{c.summary}</p>{c.nextAction && <p><strong>Action suivante :</strong> {c.nextAction}</p>}</li>)}</ol>{!contacts.some(c=>!type||type===c.channel) && <p>Aucun contact pour ce filtre.</p>}</section>
 <section className="m-panel overflow-x-auto"><h2 className="font-semibold mb-2">Réclamations</h2><table className="w-full text-left text-sm"><thead><tr>{["Adhérent / réception","Motif / rattachement","Statut / priorité","Traitement"].map(s=><th className="p-2" key={s}>{s}</th>)}</tr></thead><tbody>{shown.map(p=><ComplaintRow key={`${p.id}-${p.revision}`} p={p} name={name(p.householdId,p.adherentName)}/>)}{!shown.length && <tr><td className="p-2" colSpan={4}>Aucune réclamation pour ces filtres.</td></tr>}</tbody></table></section>
 </div>;
}
function ComplaintRow({p,name}:{p:Complaint;name:string}) {
 const [error,setError]=useState("");const [pending,startTransition]=useTransition();const router=useRouter();
 return <><tr id={p.id} className="border-b border-border align-top"><td className="p-2"><Link className="text-brand underline" href={`/adherents/${p.householdId}?tab=contacts`}>{name}</Link><p>{p.receivedDate}</p></td><td className="p-2"><strong>{p.reason}</strong><p className="whitespace-pre-wrap">{p.description}</p>{p.link && <p><Link className="text-brand underline" href={p.link.href}>{p.link.label}</Link></p>}<Link className="text-brand underline" href={`/dossiers#${p.dossierId}`}>Dossier de traitement</Link></td><td className="p-2"><BusinessStatus status={p.status}/><p><BusinessStatus status={p.priority}/></p></td><td className="p-2">
 {p.status!=="Clôturée" ? <form className="space-y-2" onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);setError("");startTransition(async()=>{const r=await updateComplaintAction(p.id,p.revision,{status:d.get("status"),priority:d.get("priority"),response:d.get("response")});if(r.error)setError(r.error);else router.refresh();});}}><fieldset disabled={pending} className="space-y-2"><label><span className="m-label">Statut</span><select className="m-field" name="status" defaultValue={p.status}>{complaintTransitions(p.status).map(s=><option key={s}>{s}</option>)}</select></label><label><span className="m-label">Priorité</span><select className="m-field" name="priority" defaultValue={p.priority}>{DOSSIER_PRIORITIES.map(s=><option key={s}>{s}</option>)}</select></label><label><span className="m-label">Réponse / résolution</span><textarea className="m-field" name="response" maxLength={5000} defaultValue={p.response}/></label></fieldset><p className="m-help">Résolution obligatoire avant clôture. Aucun message envoyé.</p><button className="m-button" disabled={pending}>Enregistrer le suivi</button>{error && <p role="alert" className="m-error">{error}</p>}</form> : <p className="whitespace-pre-wrap">{p.response}</p>}
 </td></tr><tr className="border-b border-border"><td className="p-2" colSpan={4}><details><summary className="cursor-pointer text-brand">Historique du traitement</summary><ol>{p.history.map((h,i)=><li key={i}>{formatDateTime(h.at)} · {h.status} · {h.priority}<p className="whitespace-pre-wrap">{h.response}</p></li>)}</ol></details></td></tr></>;
}
