"use client";
import { BusinessStatus } from "@/components/ui/StatusPill";
import Link from "next/link";
import { MonthlyAgenda } from "./MonthlyAgenda";
import { AppointmentForm } from "./AppointmentForm";
import { type Prospect } from "@/lib/domain/prospects";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { appointmentSlots,agendaDates,endTime,minutes,localToday,type Appointment } from "@/lib/domain/appointments";
import { appointmentContactAction } from "@/lib/domain/appointmentActions";
export function Agenda({rows,households,householdId,prospects=[],prospectId}:{prospects?:Prospect[];prospectId?:string;rows:Appointment[];households:{id:string;name:string}[];householdId?:string}){
 const [view,setView]=useState<"today"|"week"|"month">("week");const [date,setDate]=useState(localToday());
 const [editing,setEditing]=useState<Appointment|null|undefined>(householdId||prospectId?null:undefined);
 const [error,setError]=useState("");const [pending,start]=useTransition();const router=useRouter();
 const dates=agendaDates(date,view);const shown=rows.filter(p=>dates.includes(p.date));
 const first=Math.min(8,...shown.map(p=>Math.floor(minutes(p.startTime)/60)));const last=Math.max(18,...shown.map(p=>Math.ceil((minutes(p.startTime)+p.durationMinutes)/60)));
 const card=(p:Appointment)=><><BusinessStatus status={p.contactType==="prospect"?"PROSPECT":"ADHÉRENT"}/> <button className="text-brand underline text-left" onClick={()=>setEditing(p)} title={`${p.startTime}–${endTime(p.startTime,p.durationMinutes)} · ${p.adherentName} · ${p.reason}`}><strong>{p.startTime}–{endTime(p.startTime,p.durationMinutes)}</strong> · {p.adherentName}<br/>{p.reason}</button><p>{p.type} · <BusinessStatus status={p.status}/></p><Link className="underline" href={p.contactType==="prospect"?`/prospects#${p.prospectId}`:`/adherents/${p.householdId}`}>{p.contactType==="prospect"?"Fiche prospect":"Fiche adhérent"}</Link>{p.contactType!=="prospect"&&p.status==="Réalisé"&&!p.contactId&&<button className="m-button m-button--secondary" disabled={pending} onClick={()=>start(async()=>{const result=await appointmentContactAction(p.id,p.revision);setError(result.error??"");router.refresh();})}>Créer un contact</button>}{p.contactId&&<Link className="underline" href={`/adherents/${p.householdId}?tab=contacts`}>Contact créé</Link>}</>;
 return <div className="space-y-4"><Link href="/prospects" className="text-brand underline">Prospects</Link><div className="m-actionbar"><button className="m-button" onClick={()=>setEditing(null)}>Planifier un rendez-vous</button>{([['today',"Aujourd’hui"],['week',"Semaine"],['month',"Mois"]] as const).map(([key,label])=><button key={key} className="m-button m-button--secondary" aria-pressed={view===key} onClick={()=>{setView(key);if(key==="today")setDate(localToday());}}>{label}</button>)}<label>Date de référence<input className="m-field" type="date" value={date} required onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></label></div>
 {editing!==undefined&&<AppointmentForm key={editing?.id??"new"} initial={editing??undefined} householdId={householdId} prospects={prospects} prospectId={prospectId} households={households} onDone={()=>{setEditing(undefined);router.refresh();}}/>}
 {view==="week"?<div className="m-panel m-agenda-grid overflow-auto" style={{maxHeight:650}} aria-label="Créneaux de la semaine"><div style={{display:"grid",gridTemplateColumns:"64px repeat(7, minmax(160px, 1fr))",minWidth:1184}}><div className="m-agenda-day">Heure</div>{dates.map(d=><strong className="m-agenda-day" key={d}>{d}</strong>)}<div style={{height:(last-first)*160,position:"relative"}}>{Array.from({length:last-first},(_,i)=><span key={i} style={{position:"absolute",top:i*160}}>{String(first+i).padStart(2,"0")}:00</span>)}</div>{dates.map(d=><div key={d} className="border-l border-border" style={{position:"relative",height:(last-first)*160,backgroundImage:"linear-gradient(to bottom, transparent 159px, var(--m-line) 159px)",backgroundSize:"100% 160px"}}>{appointmentSlots(shown.filter(p=>p.date===d)).map(({appointment:p,lane,lanes})=>{return <button key={p.id} className="border border-border rounded bg-surface text-left text-xs overflow-hidden" style={{position:"absolute",top:(minutes(p.startTime)-first*60)*160/60,height:p.durationMinutes*160/60,width:`${100/lanes}%`,left:`${lane*100/lanes}%`,padding:3,minHeight:0}} onClick={()=>setEditing(p)} title={`${p.startTime}–${endTime(p.startTime,p.durationMinutes)} · ${p.adherentName} · ${p.reason} · ${p.status}`}><strong>{p.startTime}–{endTime(p.startTime,p.durationMinutes)}</strong><br/>{p.contactType==="prospect"?"PROSPECT":"ADHÉRENT"} · {p.adherentName} · {p.reason} · {p.status}</button>;})}</div>)}</div></div>:view==="month"?<MonthlyAgenda date={date} rows={shown} onDateChange={setDate} onEdit={setEditing} renderDetail={card}/>:<div className="space-y-3">{dates.map(d=><section className="m-panel" key={d}><h2>{d}</h2>{shown.filter(p=>p.date===d).map(p=><article key={p.id} className="mb-3 text-sm">{card(p)}</article>)}{!shown.some(p=>p.date===d)&&<p className="m-help">Aucun rendez-vous</p>}</section>)}</div>}
 {view==="week"&&<section className="m-panel"><h2>Rendez-vous de la semaine</h2>{shown.map(p=><article key={p.id} className="border-b border-border py-2 text-sm"><span>{p.date} · </span>{card(p)}</article>)}{!shown.length&&<p>Aucun rendez-vous cette semaine.</p>}</section>}{error&&<p className="m-error" role="alert">{error}</p>}</div>;
}
