"use client";
import { BusinessStatus } from "@/components/ui/StatusPill";
import Link from "next/link";
import { ProspectEditor } from "@/components/prospects/ProspectEditor";
import { PROSPECT_REASONS,type Prospect } from "@/lib/domain/prospects";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { APPOINTMENT_TYPES,APPOINTMENT_STATUSES,DURATIONS,appointmentSlots,agendaDates,endTime,minutes,localToday,type Appointment } from "@/lib/domain/appointments";
import { saveAppointmentAction,appointmentContactAction,type AppointmentResult } from "@/lib/domain/appointmentActions";
export function Agenda({rows,households,householdId,prospects=[],prospectId}:{prospects?:Prospect[];prospectId?:string;rows:Appointment[];households:{id:string;name:string}[];householdId?:string}){
 const [view,setView]=useState<"today"|"week"|"month">("week");const [date,setDate]=useState(localToday());
 const [editing,setEditing]=useState<Appointment|null|undefined>(householdId||prospectId?null:undefined);
 const [error,setError]=useState("");const [pending,start]=useTransition();const router=useRouter();
 const dates=agendaDates(date,view);const shown=rows.filter(p=>dates.includes(p.date));
 const first=Math.min(8,...shown.map(p=>Math.floor(minutes(p.startTime)/60)));const last=Math.max(18,...shown.map(p=>Math.ceil((minutes(p.startTime)+p.durationMinutes)/60)));
 const card=(p:Appointment)=><><BusinessStatus status={p.contactType==="prospect"?"PROSPECT":"ADHÉRENT"}/> <button className="text-brand underline text-left" onClick={()=>setEditing(p)} title={`${p.startTime}–${endTime(p.startTime,p.durationMinutes)} · ${p.adherentName} · ${p.reason}`}><strong>{p.startTime}–{endTime(p.startTime,p.durationMinutes)}</strong> · {p.adherentName}<br/>{p.reason}</button><p>{p.type} · <BusinessStatus status={p.status}/></p><Link className="underline" href={p.contactType==="prospect"?`/prospects#${p.prospectId}`:`/adherents/${p.householdId}`}>{p.contactType==="prospect"?"Fiche prospect":"Fiche adhérent"}</Link>{p.contactType!=="prospect"&&p.status==="Réalisé"&&!p.contactId&&<button className="m-button m-button--secondary" disabled={pending} onClick={()=>start(async()=>{const result=await appointmentContactAction(p.id,p.revision);setError(result.error??"");router.refresh();})}>Créer un contact</button>}{p.contactId&&<Link className="underline" href={`/adherents/${p.householdId}?tab=contacts`}>Contact créé</Link>}</>;
 return <div className="space-y-4"><Link href="/prospects" className="text-brand underline">Prospects</Link><div className="m-actionbar"><button className="m-button" onClick={()=>setEditing(null)}>Planifier un rendez-vous</button>{([['today',"Aujourd’hui"],['week',"Semaine"],['month',"Mois"]] as const).map(([key,label])=><button key={key} className="m-button m-button--secondary" aria-pressed={view===key} onClick={()=>{setView(key);if(key==="today")setDate(localToday());}}>{label}</button>)}<label>Date de référence<input className="m-field" type="date" value={date} required onChange={e=>{if(e.target.value)setDate(e.target.value);}}/></label></div>
 {editing!==undefined&&<AppointmentForm key={editing?.id??"new"} initial={editing??undefined} householdId={householdId} prospects={prospects} prospectId={prospectId} households={households} onDone={()=>{setEditing(undefined);router.refresh();}}/>}
 {view==="week"?<div className="m-panel m-agenda-grid overflow-auto" style={{maxHeight:650}} aria-label="Créneaux de la semaine"><div style={{display:"grid",gridTemplateColumns:"64px repeat(7, minmax(160px, 1fr))",minWidth:1184}}><div className="m-agenda-day">Heure</div>{dates.map(d=><strong className="m-agenda-day" key={d}>{d}</strong>)}<div style={{height:(last-first)*160,position:"relative"}}>{Array.from({length:last-first},(_,i)=><span key={i} style={{position:"absolute",top:i*160}}>{String(first+i).padStart(2,"0")}:00</span>)}</div>{dates.map(d=><div key={d} className="border-l border-border" style={{position:"relative",height:(last-first)*160,backgroundImage:"linear-gradient(to bottom, transparent 159px, var(--m-line) 159px)",backgroundSize:"100% 160px"}}>{appointmentSlots(shown.filter(p=>p.date===d)).map(({appointment:p,lane,lanes})=>{return <button key={p.id} className="border border-border rounded bg-surface text-left text-xs overflow-hidden" style={{position:"absolute",top:(minutes(p.startTime)-first*60)*160/60,height:p.durationMinutes*160/60,width:`${100/lanes}%`,left:`${lane*100/lanes}%`,padding:3,minHeight:0}} onClick={()=>setEditing(p)} title={`${p.startTime}–${endTime(p.startTime,p.durationMinutes)} · ${p.adherentName} · ${p.reason} · ${p.status}`}><strong>{p.startTime}–{endTime(p.startTime,p.durationMinutes)}</strong><br/>{p.contactType==="prospect"?"PROSPECT":"ADHÉRENT"} · {p.adherentName} · {p.reason} · {p.status}</button>;})}</div>)}</div></div>:<div className={view==="month"?"grid gap-3 md:grid-cols-3 xl:grid-cols-7":"space-y-3"}>{dates.map(d=><section className="m-panel" key={d}><h2>{d}</h2>{shown.filter(p=>p.date===d).map(p=><article key={p.id} className="mb-3 text-sm">{card(p)}</article>)}{!shown.some(p=>p.date===d)&&<p className="m-help">Aucun rendez-vous</p>}</section>)}</div>}
 {view==="week"&&<section className="m-panel"><h2>Rendez-vous de la semaine</h2>{shown.map(p=><article key={p.id} className="border-b border-border py-2 text-sm"><span>{p.date} · </span>{card(p)}</article>)}{!shown.length&&<p>Aucun rendez-vous cette semaine.</p>}</section>}{error&&<p className="m-error" role="alert">{error}</p>}</div>;
}
function AppointmentForm({initial,householdId,households,onDone,prospects,prospectId}:{prospects:Prospect[];prospectId?:string;initial?:Appointment;householdId?:string;households:{id:string;name:string}[];onDone:()=>void}){
 const [contactType,setContactType]=useState(initial?.contactType??(prospectId?"prospect":"adherent"));
 const [choices,setChoices]=useState(prospects);const [selectedProspect,setSelectedProspect]=useState(initial?.prospectId??prospectId??"");const [creating,setCreating]=useState(false);
 const [time,setTime]=useState(initial?.startTime??"09:00");const [duration,setDuration]=useState(initial?.durationMinutes??30);
 const [result,setResult]=useState<AppointmentResult>({});const [confirmed,setConfirmed]=useState(false);const [pending,start]=useTransition();
 return <form className="m-panel space-y-3" aria-label="Rendez-vous" onChange={()=>{setConfirmed(false);}} onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const raw:Record<string,unknown>={...Object.fromEntries(data),durationMinutes:Number(data.get("durationMinutes"))};raw.contactType=contactType;raw.householdId=contactType==="prospect"?"":initial?.householdId??raw.householdId;if(contactType==="prospect")raw.prospectId=selectedProspect;start(async()=>{const r=await saveAppointmentAction(raw,initial?.id,initial?.revision,confirmed?result.confirmation:undefined);setResult(r);setConfirmed(false);if(!r.error)onDone();});}}>
 <h2>{initial?"Modifier / déplacer le rendez-vous":"Nouveau rendez-vous"}</h2><fieldset disabled={pending} className="grid gap-3 md:grid-cols-3">
 <label>Type de contact<select className="m-field" value={contactType} disabled={!!initial} onChange={e=>setContactType(e.target.value as "adherent"|"prospect")}><option value="adherent">Adhérent</option><option value="prospect">Prospect</option></select></label>
 {contactType==="prospect"?<div><label>Prospect<select className="m-field" required value={selectedProspect} disabled={!!initial} onChange={e=>setSelectedProspect(e.target.value)}><option value="">Choisir un prospect</option>{choices.filter(p=>p.status==="actif"||p.id===selectedProspect).map(p=><option key={p.id} value={p.id}>{p.firstName} {p.lastName}</option>)}</select></label>{!initial&&<button type="button" className="m-button m-button--secondary" onClick={()=>setCreating(!creating)}>Créer un prospect</button>}{creating&&<ProspectEditor onSaved={p=>{setChoices([...choices,p]);setSelectedProspect(p.id);setCreating(false);}}/>}</div>:<label>Adhérent<select className="m-field" name="householdId" required defaultValue={initial?.householdId??householdId??""} disabled={!!initial}><option value="">Choisir</option>{households.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select></label>}
 <label>Date<input className="m-field" name="date" type="date" required defaultValue={initial?.date??localToday()}/></label>
 <label>Heure de début<input className="m-field" name="startTime" type="time" required value={time} onChange={e=>setTime(e.target.value)}/></label>
 <label>Durée<select className="m-field" name="durationMinutes" value={duration} onChange={e=>setDuration(Number(e.target.value))}>{DURATIONS.map(n=><option key={n} value={n}>{n} min</option>)}</select></label><p>Heure de fin : {time?endTime(time,duration):"—"}</p>
 <label>Type<select className="m-field" name="type" defaultValue={initial?.type}>{APPOINTMENT_TYPES.map(t=><option key={t}>{t}</option>)}</select></label>
 {contactType==="prospect"?<label>Motif du rendez-vous<select name="reason" className="m-field" defaultValue={initial?.reason??PROSPECT_REASONS[0]}>{PROSPECT_REASONS.map(r=><option key={r}>{r}</option>)}</select></label>:<label>Motif<input className="m-field" name="reason" required minLength={3} maxLength={200} defaultValue={initial?.reason}/></label>}
 <label>Statut<select className="m-field" name="status" defaultValue={initial?.status??"Planifié"}>{APPOINTMENT_STATUSES.map(s=><option key={s}>{s}</option>)}</select></label>
 <label>Notes<textarea className="m-field" name="notes" maxLength={3000} defaultValue={initial?.notes}/></label></fieldset>
 {initial&&<Link className="underline" href={initial.contactType==="prospect"?`/prospects#${initial.prospectId}`:`/adherents/${initial.householdId}`}>Ouvrir la fiche</Link>}
 {result.error&&<div className="m-error" role="alert"><p>{result.error}</p>{result.conflicts?.map(c=><p key={c}>{c}</p>)}</div>}
 {result.confirmation&&<label><input type="checkbox" checked={confirmed} onChange={e=>{e.stopPropagation();setConfirmed(e.target.checked);}}/>Je confirme le chevauchement et conserve les rendez-vous existants.</label>}
 <button className="m-button" disabled={pending}>Enregistrer</button>{" "}<button className="m-button m-button--secondary" type="button" disabled={pending} onClick={onDone}>Annuler la saisie</button>
 </form>;
}
