import { maskDemoSocialSecurityNumber } from "@/lib/domain/demoSocialSecurity";
import { pedagogicalHouseholdRecord } from "@/lib/domain/pedagogicalHouseholdRecord";
import Link from "next/link";
import { BankingSummary } from "./BankingSummary";
import { PedagogicalEstimate } from "@/components/cotisations/PedagogicalEstimate";
import type { ReactNode } from "react";
import { Card } from "@/components/ui/Card";
import { Badge,DataToVerifyBadge } from "@/components/ui/Badge";
import { QueryTabs } from "@/components/ui/QueryTabs";
import { DocumentStatusPill } from "@/components/ui/StatusPill";
import { HouseholdEditor } from "./HouseholdEditor";
import { LifecycleEditor } from "./LifecycleEditor";
import { householdTimeline,type HouseholdEvent } from "./householdTimeline";
import { RelationHistory } from "@/components/relation/RelationHistory";
import { CotisationHistory } from "@/components/cotisations/CotisationHistory";
import { PrestationHistory } from "@/components/prestations/PrestationHistory";
import { PrestationForm } from "@/components/prestations/PrestationForm";
import { DevisPecHistory } from "@/components/devisPec/DevisPecHistory";
import type { HouseholdView } from "@/lib/domain/households";
import type { CockpitData } from "@/components/cockpit/Cockpit";
import { activeAt,STATUS_LABELS } from "@/lib/domain/householdLifecycle";
import { getHouseholdFormulas } from "@/lib/domain/householdFormulas";
import { getDocumentState,getSubmissions } from "@/lib/store/runtimeStore";
import { individualCatalog2026 } from "@/lib/data/harmonie/individualCatalog";
import { upcomingAppointments,endTime,localToday } from "@/lib/domain/appointments";
import { DOCUMENT_TYPE_LABELS,MEMBER_ROLE_LABELS,type DocumentStatus } from "@/lib/domain/constants";
import { formatDate,formatDateTime } from "@/lib/utils/format";
export const HOUSEHOLD_TABS=[{key:"vue-generale",label:"Synthèse"},{key:"beneficiaires",label:"Foyer"},{key:"garanties",label:"Garanties"},{key:"prestations",label:"Dossiers & prestations"},{key:"cotisations",label:"Cotisations"},{key:"contacts",label:"Relation"},{key:"documents",label:"Documents"},{key:"historique",label:"Timeline"}];
export function householdTab(tab?:string){return tab==="contrat"?"vue-generale":tab==="pec"?"prestations":HOUSEHOLD_TABS.some(t=>t.key===tab)?tab!:"vue-generale";}
export function Household360({owner,household:h,data,tab,action}:{owner:string;household:HouseholdView;data:CockpitData;tab?:string;action?:string}){
 const id=h.householdId,base=`/adherents/${id}`,activeTab=householdTab(tab),manual=h.case?h.simulation:h.manual;
 const simulationRecord=h.case ? (h.simulation ?? pedagogicalHouseholdRecord(id)) : undefined;
 const editorRecord=h.case ? (simulationRecord ? {...simulationRecord,revision:h.simulationRevision ?? 0} : undefined) : h.manual;
 const today=localToday();const active=activeAt(h.lifecycle?.adherent,today);const status=active?"active":h.lifecycle?.adherent.status??"active";
 const members=h.beneficiaries.map(m=>({id:m.member_id,name:`${m.first_name} ${m.last_name}`,detail:`${MEMBER_ROLE_LABELS[m.role]} · ${formatDate(m.birth_date)}`}));
 const attached=members.filter(m=>activeAt(h.lifecycle?.beneficiaries[m.id],today));
 const dossiers=data.dossiers.filter(p=>p.householdId===id);const open=dossiers.filter(p=>p.status!=="Terminé");
 const anomalies=data.anomalies.filter(p=>p.householdId===id);const alerts=anomalies.filter(p=>p.status!=="Résolue");
 const appointments=upcomingAppointments(data.appointments.filter(p=>p.householdId===id));
 const events=householdTimeline(data,id,h.lifecycle,Object.fromEntries(members.map(m=>[m.id,m.name])),h.case?undefined:manual?.createdAt,manual?.bankingHistory,h.simulationHistory);
 const reference=h.assignedFormula.replace(/\s/g,"");const product=individualCatalog2026.listProducts().find(p=>p.reference===reference);const coverage=individualCatalog2026.getCoverage(reference);
 const formula=manual?getHouseholdFormulas().find(f=>f.key===manual.formulaKey)?.label:h.assignedFormula;
 const operations=data.prestations.filter(p=>p.householdId===id);const quotes=data.quotes.filter(p=>p.householdId===id);
 const plans=<section aria-label="Prochains rendez-vous"><h2 className="font-semibold mb-2">Prochains rendez-vous</h2>{appointments.slice(0,3).map(p=><div key={p.id} className="text-sm border-b border-border py-2"><Link className="text-brand underline" href="/agenda">{formatDate(p.date)} · {p.startTime}–{endTime(p.startTime,p.durationMinutes)}</Link><p>{p.type} · {p.reason} <Badge tone="brand">{p.status}</Badge></p></div>)}{!appointments.length&&<Empty>Aucun rendez-vous à venir.</Empty>}</section>;
 const queue=<section aria-label="Dossiers ouverts"><h2 className="font-semibold mb-2">Dossiers ouverts · {open.length}</h2>{open.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-2 py-2 border-b border-border"><Link className="text-sm underline text-brand" href={`/dossiers#${p.id}`}>{p.type} →</Link><div className="flex gap-1"><Badge tone={p.priority==="Urgent"?"danger":"neutral"}>{p.priority}</Badge><Badge>{p.status}</Badge></div></div>)}{!open.length&&<Empty>Aucun dossier ouvert.</Empty>}</section>;
 return <div className="m-workspace space-y-4">
 <Card><header aria-label="En-tête adhérent"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-foreground-muted">Adhérent n° {h.adherent.member_id} · {h.case?"Foyer pédagogique":"Création manuelle"}</p><h1 className="text-2xl font-semibold">{h.adherent.first_name} {h.adherent.last_name}</h1></div><Badge tone={active?"success":"neutral"}>{STATUS_LABELS[status]}</Badge></div>
 <dl className="grid gap-x-6 gap-y-2 text-sm sm:grid-cols-2 lg:grid-cols-4 mt-3"><Field label="Formule / référence">{formula??h.assignedFormula}</Field><Field label="Régime">{product?.regime??"Non renseigné"}</Field><Field label="Date d’effet">{manual?.effectiveDate?formatDate(manual.effectiveDate):"Non renseignée"}</Field><Field label="Coordonnées">{manual?<><a className="underline" href={`mailto:${manual.email}`}>{manual.email}</a><br/><a className="underline" href={`tel:${manual.phone}`}>{manual.phone}</a></>:"Non renseignées"}</Field></dl>
 <nav aria-label="Actions rapides adhérent" className="flex flex-wrap gap-2 mt-4">{(manual||h.case)&&<><Quick href={`${base}?tab=beneficiaires&action=edit`}>{h.case?"Modifier le dossier de simulation":"Modifier"}</Quick><Quick href={`${base}?tab=beneficiaires&action=add`}>Ajouter un bénéficiaire</Quick></>}<Quick href={`/agenda?householdId=${encodeURIComponent(id)}`}>Planifier un rendez-vous</Quick><Quick href={`${base}?tab=contacts&action=contact`}>Nouveau contact</Quick><Quick href={`${base}?tab=prestations&action=prestation`}>Créer une prestation</Quick><Quick href={`${base}?tab=beneficiaires&action=close`}>Clôturer l’adhérent</Quick></nav>
 {h.case&&<p className="m-help mt-2">Modification pédagogique — le cas source reste inchangé</p>}</header></Card>
 <QueryTabs basePath={base} activeKey={activeTab} tabs={HOUSEHOLD_TABS}/>
 {activeTab==="vue-generale"&&<div className="grid gap-4 lg:grid-cols-2"><div className="space-y-4"><Card><h2 className="font-semibold mb-2">Identité & contrat</h2><dl className="grid grid-cols-2 gap-3 text-sm"><Field label="Naissance">{formatDate(h.adherent.birth_date)}</Field><Field label="Organisme">{h.case?.contract.provider??"Harmonie Mutuelle"}</Field><Field label="Foyer">{id}</Field><Field label="Numéro de Sécurité sociale — Démo">{maskDemoSocialSecurityNumber(manual?.socialSecurityNumber)}</Field><Field label="Bénéficiaires rattachés">{attached.length} actif(s) / {members.length} au total</Field>{manual&&<Field label="Adresse">{manual.address}, {manual.postalCode} {manual.city}</Field>}</dl><p className="text-sm mt-3">{attached.map(m=>m.name).join(" · ")||"Aucun bénéficiaire actif"}</p><Link className="underline text-brand text-sm" href={`${base}?tab=beneficiaires`}>Consulter le foyer →</Link></Card><Card>{queue}</Card><PedagogicalEstimate household={h}/><BankingSummary banking={manual?.banking}/></div><div className="space-y-4"><Card><h2 className="font-semibold mb-2">Alertes importantes · {alerts.length}</h2>{!active&&<p className="text-sm mb-2"><Badge>{STATUS_LABELS[status]}</Badge> Historique conservé · effet {h.lifecycle?.adherent.endDate}</p>}{alerts.slice(0,3).map(p=><p className="text-sm mb-2" key={p.id}><Badge tone={p.severity==="Bloquante"?"danger":"warning"}>{p.severity}</Badge> <Link className="underline text-brand" href={`/flux-anomalies#${p.id}`}>{p.cause} →</Link></p>)}{!alerts.length&&<Empty>Aucune anomalie ouverte.</Empty>}</Card><Card>{plans}</Card><Card><h2 className="font-semibold">Dernières opérations</h2><Timeline events={events.slice(0,4)}/><Link className="text-sm text-brand underline" href={`${base}?tab=historique`}>Toute la timeline →</Link></Card></div></div>}
 {activeTab==="beneficiaires"&&<div className="space-y-3"><Card><h2 className="font-semibold">Titulaire</h2><p>{h.adherent.first_name} {h.adherent.last_name} · {formatDate(h.adherent.birth_date)} <Badge tone={active?"success":"neutral"}>{STATUS_LABELS[status]}</Badge></p></Card>
 <LifecycleEditor showAdherent={false} key={`${id}-${action??""}`} id={id} initialClose={action==="close"} lifecycle={h.lifecycle} members={members}/>
 {editorRecord&&<details open={action==="edit"||action==="add"} className="m-panel"><summary className="cursor-pointer text-brand font-medium">Coordonnées du titulaire et des bénéficiaires</summary><HouseholdEditor key={`${id}-${action??""}-${editorRecord.revision}`} record={editorRecord} formulas={getHouseholdFormulas()} lifecycle={h.lifecycle} hideLifecycle initialAction={action==="edit"||action==="add"?action:undefined}/></details>}</div>}
 {activeTab==="garanties"&&<Card><h2 className="font-semibold">{formula??h.assignedFormula} · 2026</h2><p className="text-sm text-foreground-muted mb-3">{product?.family??"Formule d’exercice"} · {product?.regime??"Régime non renseigné"}</p>{coverage.verified>0&&<p className="text-sm mb-2"><Badge tone="success">Vérifié</Badge> {coverage.verified} prestation(s) documentée(s) pour cette référence.</p>}{(coverage.needs_review>0||!coverage.verified)&&<p className="text-sm mb-2"><DataToVerifyBadge/>{coverage.needs_review>0&&` · ${coverage.needs_review} donnée(s) en attente de validation`}</p>}<p className="text-sm mb-3">Le statut s’applique à chaque garantie ; les conditions restent à contrôler.</p><Link className="m-button m-button--secondary" href="/garanties">Consulter le détail Garanties</Link></Card>}
 {activeTab==="prestations"&&<div className="space-y-4"><Card>{queue}</Card>{action==="prestation"&&<section><h2 className="font-semibold mb-2">Nouvelle prestation</h2><PrestationForm defaultHouseholdId={id} households={[{id,name:`${h.adherent.first_name} ${h.adherent.last_name}`,lifecycle:h.lifecycle,members:h.household.members.map(m=>({id:m.member_id,name:`${m.first_name} ${m.last_name}`}))}]}/></section>}<section id="prestations"><h2 className="font-semibold mb-2">Prestations · {operations.length}</h2><PrestationHistory owner={owner} householdId={id}/></section><section id="pec"><h2 className="font-semibold mb-2">PEC / Devis · {quotes.length}</h2><DevisPecHistory owner={owner} householdId={id}/></section><Card><h2 className="font-semibold">Anomalies liées</h2>{anomalies.map(p=><p className="text-sm py-2" key={p.id}><Badge>{p.status}</Badge> <Link className="underline text-brand" href={`/flux-anomalies#${p.id}`}>{p.type} →</Link></p>)}{!anomalies.length&&<Empty>Aucune anomalie liée.</Empty>}</Card></div>}
 {activeTab==="cotisations"&&<div className="space-y-4"><PedagogicalEstimate household={h}/><CotisationHistory owner={owner} householdId={id}/></div>}
 {activeTab==="contacts"&&<div className="space-y-4"><RelationHistory key={action??"relation"} owner={owner} householdId={id} initialContact={action==="contact"}/><Card>{plans}</Card><Card><h2 className="font-semibold">Historique des rendez-vous</h2><Timeline events={events.filter(e=>e.type==="Rendez-vous")}/></Card></div>}
 {activeTab==="documents"&&<Card><h2 className="font-semibold mb-2">Documents liés</h2>{h.case&&<p className="m-help">Les documents appartiennent au cas pédagogique source et ne sont pas modifiés par les changements du dossier de simulation.</p>}{h.case?<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="py-2">Document</th><th>Bénéficiaire</th><th>Date</th><th>Statut</th></tr></thead><tbody>{h.case.documents.map(doc=><tr key={doc.document_id} className="border-t border-border"><td className="py-2"><Link className="underline text-brand" href={`/cas-pratiques/${h.case!.case_id}`}>{DOCUMENT_TYPE_LABELS[doc.document_type]??doc.document_type}</Link></td><td>{h.case!.household.members.find(m=>m.member_id===doc.beneficiary_id)?.first_name??doc.beneficiary_id??"—"}</td><td>{doc.document_date?formatDate(doc.document_date):"—"}</td><td><DocumentStatusPill status={(getDocumentState(owner,doc.document_id).status??doc.status) as DocumentStatus}/></td></tr>)}</tbody></table></div>:<Empty>Aucun document lié disponible.</Empty>}</Card>}
 {activeTab==="historique"&&<Card><h2 className="font-semibold mb-2">Timeline 360°</h2><Timeline events={events}/>{h.case&&<details className="mt-3"><summary>Historique pédagogique</summary><ul>{getSubmissions(owner,h.case.case_id).map((s,i)=><li key={i}><Link className="underline" href={`/cas-pratiques/${h.case!.case_id}`}>{formatDateTime(s.submittedAt)} · Soumission {s.score}/{s.maxScore}</Link></li>)}</ul></details>}</Card>}
 </div>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <div className="min-w-0"><dt className="text-xs text-foreground-muted">{label}</dt><dd className="font-medium break-words">{children}</dd></div>;}
function Quick({href,children}:{href:string;children:ReactNode}){return <Link className="m-button m-button--secondary text-sm" href={href}>{children}</Link>;}
function Empty({children}:{children:ReactNode}){return <p className="text-sm text-foreground-muted py-2">{children}</p>;}
export function Timeline({events}:{events:HouseholdEvent[]}){return <ol aria-label="Événements chronologiques" className="text-sm">{events.map(e=><li key={e.id} className="grid gap-1 border-b border-border py-2 last:border-0"><div className="flex flex-wrap gap-2 items-center"><time dateTime={e.at} className="text-xs text-foreground-muted">{e.at.includes("T")?formatDateTime(e.at):formatDate(e.at)}</time><Badge>{e.type}</Badge></div><Link className="text-brand underline break-words" href={e.href}>{e.summary.length>180?`${e.summary.slice(0,177)}…`:e.summary} →</Link></li>)}{!events.length&&<li className="text-foreground-muted py-2">Aucun événement enregistré.</li>}</ol>;}
