import { afterAll, beforeAll, expect, it, vi } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { filterOperationalAnomalies } from "./operationalAnomalies";
import type { PrestationInput } from "./prestations";
vi.mock("server-only",()=>({}));
vi.mock("next/cache",()=>({revalidatePath:vi.fn()}));
vi.mock("@/lib/store/session",()=>({getSession:vi.fn(async()=>({userId:"a"}))}));
const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mutalia-anomalies-"));
let db:typeof import("../db").db;
let store:typeof import("../store/runtimeStore");
let service:typeof import("./prestationService");
let input:PrestationInput;
beforeAll(async()=>{
 process.env.MUTALIA_DATA_DIR=dir;
 db=(await import("../db")).db;store=await import("../store/runtimeStore");service=await import("./prestationService");
 const h=(await import("./households")).getAllHouseholds("a")[0];
 input={householdId:h.householdId,memberId:h.adherent.member_id,act:"Exercice",careDate:"2026-09-01",billed:80,brss:35,amoRate:0.7,guaranteeMode:"percent_brss",guaranteeValue:150,contractSource:"Exercice fictif page 1",contractVerified:true};
});
afterAll(()=>{db?.close();fs.rmSync(dir,{recursive:true,force:true});});
it("creates a persistent anomaly atomically with the prestation and does not duplicate it",()=>{
 const p=service.receivePrestation("a",{...input,contractVerified:false});
 const raw=db.prepare("SELECT payload FROM codex_learner_work WHERE owner=?").get("a") as {payload:string};
 expect(Object.values(JSON.parse(raw.payload).operationalAnomalies)).toHaveLength(1);
 const first=store.getOperationalAnomalies("a").find(a=>a.prestationId===p.id)!;
 expect(first).toMatchObject({severity:"Bloquante",status:"À analyser",conditionActive:true,householdId:p.householdId,dossierId:p.dossierId});
 expect(store.getOperationalAnomalies("a").find(a=>a.id===first.id)).toEqual(first);
 expect(()=>store.updateOperationalAnomaly("a",first.id,first.revision,{status:"Résolue",resolution:"Garantie supposée corrigée"})).toThrow("Corrigez d’abord");
});
it("preserves analysis notes, allows resolution only after correction and synchronizes the dossier",()=>{
 let p=service.receivePrestation("a",{...input,contractSource:""});
 let a=store.getOperationalAnomalies("a").find(a=>a.prestationId===p.id)!;
 a=store.updateOperationalAnomaly("a",a.id,a.revision,{status:"En cours",resolution:"Recherche du justificatif"});
 p=service.correctPrestation("a",p.id,p.revision,input);
 a=store.getOperationalAnomalies("a").find(x=>x.id===a.id)!;
 expect(a).toMatchObject({conditionActive:false,status:"En cours"});
 expect(()=>store.updateOperationalAnomaly("a",a.id,a.revision,{status:"Résolue",resolution:""})).toThrow("10 caractères");
 p=service.advancePrestation("a",p.id,p.revision,"À contrôler");p=service.advancePrestation("a",p.id,p.revision,"Calculée");p=service.advancePrestation("a",p.id,p.revision,"Validée");
 expect(store.getDossierStates("a")[p.dossierId].status).toBe("À traiter");
 a=store.updateOperationalAnomaly("a",a.id,a.revision,{status:"Résolue",resolution:"Source vérifiée et calcul contrôlé"});
 expect(a.history.some(h=>h.resolution==="Recherche du justificatif")).toBe(true);
 expect(a.history.at(-1)?.resolution).toBe("Source vérifiée et calcul contrôlé");
 expect(store.getDossierStates("a")[p.dossierId].status).toBe("Terminé");
 expect(store.getPrestations("a").find(x=>x.id===p.id)?.status).toBe("Validée");
});
it("reopens a recurring control with the same id and keeps previous resolution history",()=>{
 let p=service.receivePrestation("a",{...input,contractVerified:false});
 let a=store.getOperationalAnomalies("a").find(a=>a.prestationId===p.id)!;
 p=service.correctPrestation("a",p.id,p.revision,input);
 a=store.getOperationalAnomalies("a").find(x=>x.id===a.id)!;
 a=store.updateOperationalAnomaly("a",a.id,a.revision,{status:"Résolue",resolution:"Garantie contrôlée dans la source"});
 service.correctPrestation("a",p.id,p.revision,{...input,contractVerified:false});
 const reopened=store.getOperationalAnomalies("a").find(x=>x.id===a.id)!;
 expect(reopened).toMatchObject({status:"À analyser",conditionActive:true,resolution:""});
 expect(reopened.history.some(h=>h.resolution==="Garantie contrôlée dans la source")).toBe(true);
 expect(store.getOperationalAnomalies("a").filter(x=>x.prestationId===p.id)).toHaveLength(1);
});
it("keeps AMO controls active until a new successful calculation confirms the correction",()=>{
 let p=service.receivePrestation("a",{...input,billed:1});
 p=service.advancePrestation("a",p.id,p.revision,"À contrôler");p=service.advancePrestation("a",p.id,p.revision,"Calculée");
 let a=store.getOperationalAnomalies("a").find(x=>x.prestationId===p.id)!;
 expect(a.type).toBe("Incohérence AMO / facturé");
 p=service.correctPrestation("a",p.id,p.revision,input);
 a=store.getOperationalAnomalies("a").find(x=>x.id===a.id)!;
 expect(a.conditionActive).toBe(true);
 expect(()=>store.updateOperationalAnomaly("a",a.id,a.revision,{status:"Résolue",resolution:"Montants corrigés sans recalcul"})).toThrow("Corrigez");
 service.advancePrestation("a",p.id,p.revision,"Calculée");
 expect(store.getOperationalAnomalies("a").find(x=>x.id===a.id)?.conditionActive).toBe(false);
});
it("does not close a dossier while another control is active",async()=>{
 const {getHouseholdFormulas}=await import("./householdFormulas");
 const h=store.createManualHousehold("multiple",{firstName:"Démo",lastName:"Exemple",birthDate:"1990-01-01",email:"demo@example.invalid",phone:"0100000000",address:"1 rue Exemple",postalCode:"75001",city:"Paris",effectiveDate:"2026-09-05",formulaKey:getHouseholdFormulas()[0].key});
 let p=service.receivePrestation("multiple",{...input,householdId:h.id,memberId:h.memberId,contractVerified:false});
 expect(store.getOperationalAnomalies("multiple")).toHaveLength(2);
 p=service.correctPrestation("multiple",p.id,p.revision,{...input,householdId:h.id,memberId:h.memberId});
 const a=store.getOperationalAnomalies("multiple").find(a=>a.id.endsWith("-contract"))!;
 store.updateOperationalAnomaly("multiple",a.id,a.revision,{status:"Résolue",resolution:"Garantie documentaire contrôlée"});
 expect(store.getDossierStates("multiple")[p.dossierId].status).toBe("Incomplet");
});
it("backfills earlier prestations once and isolates accounts and revisions",()=>{
 const p=service.receivePrestation("legacy",{...input,contractVerified:false});
 const row=db.prepare("SELECT payload FROM codex_learner_work WHERE owner=?").get("legacy") as {payload:string};
 const data=JSON.parse(row.payload);delete data.operationalAnomalies;
 db.prepare("UPDATE codex_learner_work SET payload=? WHERE owner=?").run(JSON.stringify(data),"legacy");
 const a=store.getOperationalAnomalies("legacy")[0];
 expect(a.prestationId).toBe(p.id);expect(store.getOperationalAnomalies("legacy")).toEqual([a]);
 expect(()=>store.updateOperationalAnomaly("other",a.id,a.revision,{status:"En cours",resolution:""})).toThrow("introuvable");
 store.updateOperationalAnomaly("legacy",a.id,a.revision,{status:"En cours",resolution:"Analyse"});
 expect(()=>store.updateOperationalAnomaly("legacy",a.id,a.revision,{status:"En cours",resolution:""})).toThrow("autre onglet");
 expect(store.getOperationalAnomalies("other")).toEqual([]);
});
it("combines all filters and sorts severity before age",()=>{
 const a=store.getOperationalAnomalies("a")[0];
 const rows=[{...a,id:"minor",severity:"Mineure" as const,createdAt:"2026-01-01"},{...a,id:"new",createdAt:"2026-09-02"},{...a,id:"old",createdAt:"2026-09-01"}];
 expect(filterOperationalAnomalies(rows,{}).map(a=>a.id)).toEqual(["old","new","minor"]);
 expect(filterOperationalAnomalies(rows,{severity:"Mineure",status:a.status,type:a.type}).map(a=>a.id)).toEqual(["minor"]);
 expect(filterOperationalAnomalies(rows,{severity:"Majeure"})).toEqual([]);
});
it("authenticates treatment and revalidates the linked views",async()=>{
 const {updateAnomalyAction}=await import("./operationalAnomalyActions");
 const {getSession}=await import("../store/session");const {revalidatePath}=await import("next/cache");
 const a=store.getOperationalAnomalies("a")[0];
 vi.mocked(getSession).mockRejectedValueOnce(new Error("Connexion requise"));
 await expect(updateAnomalyAction(a.id,a.revision,{status:"En cours",resolution:"Analyse"})).rejects.toThrow("Connexion requise");
 expect(await updateAnomalyAction(a.id,a.revision,{status:"En cours",resolution:"Analyse"})).toEqual({});
 for(const route of ["/flux-anomalies","/prestations","/dossiers","/cockpit"])expect(revalidatePath).toHaveBeenCalledWith(route);
 expect(await updateAnomalyAction(a.id,a.revision,{status:"inventé",resolution:""})).toHaveProperty("error");
});
