import { beforeAll,afterAll,it,expect,vi } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createHash } from "node:crypto";
import { PDFDocument } from "pdf-lib";
import { DemoSocialSecuritySchema,generateDemoSocialSecurityNumber,maskDemoSocialSecurityNumber,normalizeDemoNir } from "@/lib/domain/demoSocialSecurity";
vi.mock("server-only",()=>({}));
vi.mock("./resolveHealthInsuranceFund",()=>({resolveHealthInsuranceFund:vi.fn(async()=>({source:"Vérification requise",name:"Caisse d’Assurance Maladie à vérifier",address:["Adresse CPAM à vérifier"]}))}));
const dir=fs.mkdtempSync(path.join(os.tmpdir(),"mutalia-amo-"));
let db:typeof import("@/lib/db").db;
let store:typeof import("@/lib/store/runtimeStore");
let service:typeof import("./amoStatementService");
beforeAll(async()=>{process.env.MUTALIA_DATA_DIR=dir;db=(await import("@/lib/db")).db;store=await import("@/lib/store/runtimeStore");service=await import("./amoStatementService");});
afterAll(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true});});
it("accepts only explicitly synthetic identifiers, normalizes and masks them",()=>{
 const value=generateDemoSocialSecurityNumber();expect(value).toMatch(/^DEMO\d{15}$/);
 expect(DemoSocialSecuritySchema.parse(value)).toBe(value);
 expect(DemoSocialSecuritySchema.safeParse("180017512345642").success).toBe(false);
 expect(normalizeDemoNir("DEMO 123 456 789 012 345")).toBe("DEMO123456789012345");
 expect(maskDemoSocialSecurityNumber(value)).not.toContain(value);
});
it("generates an A4 copy for another beneficiary, preserves sources, owner isolation and NIR reset",async()=>{
 const {getAllCases}=await import("@/lib/data/loaders");
 const {pedagogicalHouseholdRecord}=await import("@/lib/domain/pedagogicalHouseholdRecord");
 const {searchByDemoNir,buildSearchIndex}=await import("@/lib/domain/search");
 const {AMO_TEMPLATE}=await import("./amoStatementPdf");
 const digest=(file:string)=>createHash("sha256").update(fs.readFileSync(file)).digest("hex");
 const before=digest(AMO_TEMPLATE),png=AMO_TEMPLATE.replace(/pdf$/,"png"),beforePng=digest(png),sources=JSON.stringify(getAllCases());
 const c=getAllCases().find(c=>c.household.members.length>1)!,original=pedagogicalHouseholdRecord(c.household.household_id)!;
 const number=generateDemoSocialSecurityNumber();
 store.updateManualHousehold("amo-a",original.id,0,{...original,socialSecurityNumber:number,address:"1 rue Démonstration",postalCode:"45130",city:"Meung-sur-Loire"});
 expect(searchByDemoNir("amo-a",number.replace(/(\d{3})/g,"$1 "))).toHaveLength(1);
 expect(searchByDemoNir("amo-b",number)).toHaveLength(0);
 expect(JSON.stringify(buildSearchIndex("amo-a"))).not.toContain(number);
 expect(JSON.stringify(searchByDemoNir("amo-a",number))).not.toContain(number);
 const input={caseId:c.case_id,memberId:c.household.members[1].member_id,periodStart:"2026-09-01",periodEnd:"2026-09-30",careDate:"2026-09-10",act:"Prothèse dentaire pédagogique",paid:440,brss:120,amoRate:60};
 const generated=await service.generateAmoStatement("amo-a",input);
 const doc=service.readAmoStatement("amo-a",generated.id)!;
 expect(doc.filename).toMatch(/^decompte-AMO-DEMO-CASE-\d+-\d{4}-\d{2}-\d{2}\.pdf$/);
 const pdf=await PDFDocument.load(doc.pdf);expect(pdf.getPageCount()).toBe(1);expect(pdf.getPages()[0].getWidth()).toBeCloseTo(595.275,2);
 const snapshot=JSON.parse((db.prepare("SELECT snapshot FROM pedagogical_amo_documents WHERE id=?").get(generated.id) as {snapshot:string}).snapshot);
 expect(snapshot.reimbursed).toBe(72);expect(snapshot.beneficiary).toBe(`${c.household.members[1].first_name} ${c.household.members[1].last_name}`);
 expect(service.readAmoStatement("amo-b",generated.id)).toBeUndefined();expect(service.listAmoStatements("amo-b")).toEqual([]);
 expect(JSON.stringify(service.listAmoStatements("amo-a"))).not.toContain(number);
 await expect(service.generateAmoStatement("amo-b",input)).rejects.toThrow("NIR Démo");
 await expect(service.generateAmoStatement("amo-a",{...input,memberId:"foreign"})).rejects.toThrow("Bénéficiaire");
 fs.writeFileSync("/tmp/mutalia-amo-review.pdf",doc.pdf);
 store.resetPedagogicalHousehold("amo-a",original.id,1,true);
 expect(searchByDemoNir("amo-a",number)).toEqual([]);expect(service.readAmoStatement("amo-a",generated.id)).toBeTruthy();
 expect(digest(AMO_TEMPLATE)).toBe(before);expect(digest(png)).toBe(beforePng);expect(JSON.stringify(getAllCases())).toBe(sources);
});
